### ISSUE TITLE
White square

### ISSUE THREAD

**Issue by Madis0** [Madis0/firefox-desaturate-favicons#2]
[An user](https://addons.mozilla.org/en-US/firefox/addon/firefox-desaturate-favicons/reviews/952209/) is seeing white squares instead of grayscale icons. I could not reproduce it on latest Nightly though, even with VivaldiFox which has a related feature.

**Comment by SavageCore** [comment]
This has just started happening for me as well in `60.0.1`, anything I can do to help debug?

**Comment by Madis0** [comment]
Well, you could try to find what causes it, aka what sites does it happen or when (such as after the page has loaded). Checking the console might help too.

**Comment by SavageCore** [comment]
Browser Console does display some errors, missed that before. 

```Blocked moz-extension://70891487-436e-43a6-ae99-318da623dc5f/_generated_background_page.html in page moz-extension://70891487-436e-43a6-ae99-318da623dc5f/_generated_background_page.html from extracting canvas data because no user input was detected. moz-extension://70891487-436e-43a6-ae99-318da623dc5f/js/background.js:174.```

It happens on all sites

1. Start Firefox
1. Open tab 1
1. Open and switch to tab 2
1. Tab 1 has white icon

Perhaps some configuration blocking canvas access? I've tested in safe mode so shouldn't be any privacy related addons.

**Comment by Madis0** [comment]
If it isn't an add-on, maybe you have enabled `privacy.resistFingerprinting` in _about:config_ ? That is known to break a of things, despite good intentions.

**Comment by SavageCore** [comment]
Yup, confirmed it's caused by `privacy.resistFingerprinting`.
